#
#
#BOF
---
#######################################################################################################################
# 
#######################################################################################################################
#
installDependencies:
  - ca-certificates
#
installPackages:
  - nfs-common

#
...
#EOF