#
#
#BOF
---
#######################################################################################################################
# 
#######################################################################################################################
#
installDependencies:
  - ca-certificates
  - jq
#
installPackages:
  - helm
#
...
#EOF